
project_id = "ylqhmufqrrprgklflgiw"

[[functions]]
name = "ai-recipe-suggestions"
verify_jwt = true

[[functions]]
name = "generate-recipe-from-fridge"
verify_jwt = true

[[functions]]
name = "scrape-recipe"
verify_jwt = false
timeout_ms = 15000

[[functions]]
name = "ai-recipe-parser"
verify_jwt = false

[[functions]]
name = "transcribe-voice"
verify_jwt = true

[[functions]]
name = "ai-memory-insights"
verify_jwt = true

[[functions]]
name = "extract-recipe-from-image"
verify_jwt = false

[[functions]]
name = "enhance-recipe-instructions"
verify_jwt = false

[[functions]]
name = "realtime-chef-assistant"
verify_jwt = false

[[functions]]
name = "generate-baby-food"
verify_jwt = true
